<a href="https://colab.research.google.com/github/erjavaid/ensemble-technique/blob/main/Boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Xg boostin,Gradient boosting,ADaboostin**


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Classification
from sklearn.datasets import make_classification

In [3]:
X,y=make_classification(n_samples=1000,n_classes=2,n_features=4,n_informative=2,n_redundant=0,random_state=1)

In [4]:
y

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,

In [5]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [6]:
X_train.shape

(700, 4)

In [7]:
# import Xg,ada nd gradient boost
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [8]:
xg=XGBClassifier()
ada=AdaBoostClassifier()
gb=GradientBoostingClassifier()

In [9]:
xg.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [10]:
ada.fit(X_train,y_train)

AdaBoostClassifier()

In [11]:
# prediction
y_pred=ada.predict(X_test)

In [12]:
# performance of the model
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [13]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8566666666666667
[[126  25]
 [ 18 131]]
              precision    recall  f1-score   support

           0       0.88      0.83      0.85       151
           1       0.84      0.88      0.86       149

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300



In [14]:
xg.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [15]:
y_pre=xg.predict(X_test)

In [16]:
# performance
print(accuracy_score(y_test,y_pre))
print(confusion_matrix(y_test,y_pre))
print(classification_report(y_test,y_pre))

0.8333333333333334
[[129  22]
 [ 28 121]]
              precision    recall  f1-score   support

           0       0.82      0.85      0.84       151
           1       0.85      0.81      0.83       149

    accuracy                           0.83       300
   macro avg       0.83      0.83      0.83       300
weighted avg       0.83      0.83      0.83       300



In [17]:
gb.fit(X_train,y_train)

GradientBoostingClassifier()

In [18]:
y_pret=gb.predict(X_test)

In [19]:
#performance
print(accuracy_score(y_test,y_pret))
print(confusion_matrix(y_test,y_pret))
print(classification_report(y_test,y_pret))

0.8566666666666667
[[128  23]
 [ 20 129]]
              precision    recall  f1-score   support

           0       0.86      0.85      0.86       151
           1       0.85      0.87      0.86       149

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300



In [20]:
# regression using xg,ada,gradient
from sklearn.datasets import make_regression

In [21]:
L,m=make_regression(n_samples=1000,n_features=4,n_informative=2,n_targets=1,noise=0.1,random_state=42)

In [22]:
# train and test split
from sklearn.model_selection import train_test_split
L_train,L_test,m_train,m_test=train_test_split(L,m,test_size=0.3,random_state=1)

In [23]:
# train the model using xg,ada,gradient regressor
from xgboost import XGBRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor


In [24]:
# make objects
xg=XGBRegressor()
ada=AdaBoostRegressor()
gb=GradientBoostingRegressor()

In [25]:
xg.fit(L_train,m_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [26]:
# predict
m_predt=xg.predict(L_test)

In [27]:
# performnce of the model
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [28]:
score=r2_score(m_test,m_predt)
print(score)

0.9971917700415381


In [29]:
ada.fit(L_train,m_train)

AdaBoostRegressor()

In [30]:
# predict
m_predi=ada.predict(L_test)

In [31]:
# performance of the moel
score=r2_score(m_test,m_predi)
print(score)

0.9693573676846174


In [32]:
gb.fit(L_train,m_train)

GradientBoostingRegressor()

In [33]:
# prediction
m_pret=gb.predict(L_test)

In [34]:
# performance
score=r2_score(m_test,m_pret)
print(score)

0.9978158517913206
