<a href="https://colab.research.google.com/github/erjavaid/ensemble-technique/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pands as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'pands'

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y=make_classification(n_samples=1000,n_features=3,n_classes=2,random_state=123,n_redundant=1)

In [4]:
X

array([[ 0.81850319,  1.13681556,  0.09931091],
       [ 1.15067323, -1.02790787, -1.19062269],
       [ 1.26724161,  0.73560882, -0.36518134],
       ...,
       [ 2.08592448, -0.6941058 , -1.56605023],
       [ 0.32959706, -1.2780663 , -0.83929964],
       [ 1.78778744, -0.70764567, -1.39932976]])

In [5]:
y

array([1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,

In [7]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
X_train.shape

(800, 3)

In [10]:
# build the model using knn
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
# prediction
y_pred=knn.predict(X_test)

In [12]:
# performance of the model
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.99
[[103   1]
 [  1  95]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       104
           1       0.99      0.99      0.99        96

    accuracy                           0.99       200
   macro avg       0.99      0.99      0.99       200
weighted avg       0.99      0.99      0.99       200



In [13]:
# regression knn
from sklearn.datasets import make_regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [14]:
L,m=make_regression(n_samples=1000,n_features=3,n_targets=1,noise=10,random_state=42)

In [15]:
# train test
X_train, X_test, y_train, y_test = train_test_split(L, m, test_size=0.2, random_state=42)

In [16]:
# model buld
knr=KNeighborsRegressor(n_neighbors=5,algorithm='auto')
knr.fit(X_train,y_train)

KNeighborsRegressor()

In [17]:
# prediction
y_predit=knr.predict(X_test)

In [18]:
# performance
score=r2_score(y_test,y_predit)
print(score)

0.9674011480499856


In [20]:
X_test

array([[-5.95661294e-01, -6.53766339e-01,  1.37443809e+00],
       [ 4.20972944e-01,  6.98828420e-01,  4.92018848e-01],
       [-4.88849422e-01,  1.54324353e+00, -1.11961743e+00],
       [ 1.18570415e+00,  5.36652753e-01,  7.18953311e-01],
       [-1.12548905e+00,  2.79968626e-01,  2.44575198e+00],
       [-1.01475673e+00, -5.81680914e-01, -6.49277545e-01],
       [ 1.49072614e+00, -2.13442871e-01,  1.48667457e-01],
       [ 6.02302099e-02, -2.65138754e-02,  2.46324211e+00],
       [-9.60598997e-02,  2.56008454e+00,  1.14927333e+00],
       [-9.95815395e-01, -4.08100839e-01,  6.51136242e-01],
       [-1.41836573e+00,  9.32590832e-01, -1.76080881e+00],
       [ 1.31759754e+00,  1.68460976e-01, -1.00654257e+00],
       [-4.83061052e-01,  8.95038314e-01,  1.46793012e-01],
       [-1.14300491e+00,  6.38730222e-01,  1.63343153e+00],
       [ 1.42730678e-02,  7.30764119e-01, -9.53939419e-01],
       [-9.04316625e-01,  2.59722502e-01,  6.38592459e-01],
       [-2.75149051e-02, -2.87226221e+00

In [21]:
y_predit

array([-6.08297167e+01,  1.18120130e+02,  6.92886006e+01,  1.85259651e+02,
        1.30754737e+01, -1.56161372e+02,  1.26544799e+02,  8.69657129e+01,
        1.65072237e+02, -1.06572268e+02, -8.93729657e+01,  1.12820499e+02,
        2.99340905e+01, -1.77676322e+01,  2.12633572e+01, -4.51903855e+01,
       -1.40476065e+02,  6.01385141e+01, -9.88533628e+00,  4.81395945e+01,
        1.01273641e+02,  4.17346725e+01, -1.33266554e+02,  2.05246009e+00,
       -1.52746084e+02,  6.93438123e+01, -7.82060473e+00, -8.78275465e+01,
       -6.22898339e+01, -5.65759681e+01,  1.26382712e+02, -6.16454887e+01,
        7.61480728e+01, -2.21835246e+02,  4.25385229e+01, -1.74082070e+01,
       -8.34912447e+01,  1.66664100e+02, -9.84106629e+01,  2.93457251e+02,
        2.89905745e+01,  9.32023736e+01, -5.61460580e+01,  9.60290120e+01,
        7.96632920e+01,  1.56578939e+02, -3.45719881e+01,  6.46857230e+01,
       -1.09938526e+02,  4.57093532e+01,  1.93667535e+02, -4.18431280e+01,
       -9.88470236e+01,  